### ISSUE TITLE
nelsnmp 0.2.6 breaks nelmon script check_admin_up_oper_down.py

### ISSUE THREAD

**Issue by pablodav** [networklore/nelsnmp#8]
see this log with nelsnmp 0.2.6: 

```shell
/usr/local/bin/nm_check_admin_up_oper_down -P 2c -H ADDRESS -c -C COMMUNITY -al 'UPLINK|Connection'
Traceback (most recent call last):
  File "/usr/local/bin/nm_check_admin_up_oper_down", line 11, in <module>
    load_entry_point('nelmon==1.3.6', 'console_scripts', 'nm_check_admin_up_oper_down')()
  File "/usr/local/lib/python2.7/dist-packages/nelmon/cli/check_admin_up_oper_down.py", line 84, in main
    var_binds = snmp.get(*oidlist)
  File "/usr/local/lib/python2.7/dist-packages/nelsnmp/snmp.py", line 236, in get
    timeout=self.timeout,
AttributeError: 'NelmonSnmp' object has no attribute 'timeout'
```

But if I downgrade to nelsnmp `0.2.5` it works fine.

**Comment by ogenstad** [comment]
Fixed in nelmon 1.3.6.
